### ISSUE TITLE
我debug时，遇到只调用getTicketToken，没有调用saveTicketToken的情况

### ISSUE THREAD

**Issue by alsosweet** [liuxiaodong/weixin-device-demo#1]
我debug时，遇到只调用getTicketToken，没有调用saveTicketToken的情况。导致报"获取 jsapi 签名出错" ,没有获得token。 在mac 本地运行的。请问是什么原因

**Comment by liuxiaodong** [comment]
因为项目中一个依赖问题导致的。我现在已经更新了，你在 pull 一下最新代码并 npm install 一下应该就 OK 了

**Comment by alsosweet** [comment]
嗯 、测试OK
